version: '3.7'

services:
  reverse_proxy:
    image: nginx:1.19
    container_name: reverse_proxy
    volumes:
      - ./config/:/etc/nginx/conf.d/
      - ./certificates/:/etc/ssl/
    networks:
      main-net:
        ipv4_address: 172.30.1.0

networks:
  main-net:
    external: true